drop user GTRAXXX;

drop tablespace GTRAXXX_DATA including contents cascade constraints;

create tablespace GTRAXXX_DATA datafile
'c:\DEV\TOOLS\oraclexe\app\oracle\oradata\XE\gtraxxx_data.dbf' size 100 M REUSE
AUTOEXTEND ON;

create user GTRAXXX identified by adminp;

grant connect to GTRAXXX;

grant all privileges to GTRAXXX;

CREATE TABLE GTRAXXX.USERS
(
IDENT NUMBER(10,0) NOT NULL,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
AGE NUMBER(2,0) DEFAULT 0,
ACTIVITY VARCHAR2(50),
EMAIL VARCHAR2(50) NOT NULL UNIQUE,
PASS  VARCHAR2(50) NOT NULL,
ROLE  VARCHAR2(50),
TOKEN  VARCHAR2(32) NOT NULL,
ACCEPTED NUMBER(1,0),
PRIMARY KEY(IDENT)
)TABLESPACE "GTRAXXX_DATA";

CREATE SEQUENCE GTRAXXX.USERS_SEQ START WITH 1;

grant all on GTRAXXX.USERS to GTRAXXX;
grant all on GTRAXXX.USERS_SEQ to GTRAXXX;

CREATE TABLE GTRAXXX.TRACKS
(
IDENT NUMBER(10,0) NOT NULL,
"NAME" VARCHAR2 (100) NOT NULL,
DESCRIPTION VARCHAR2(250),
ACTIVITY VARCHAR2 (20),
"FILE" VARCHAR2(200) NOT NULL UNIQUE,
USER_ID NUMBER(*,0)  NOT NULL,
STARTDATE DATE,
ENDDATE DATE,
"ACCESS" VARCHAR2(45),
START_ADDRESS VARCHAR2(100),
END_ADDRESS VARCHAR2(100),
LENGTH_KM NUMBER,
MIN_ELEVATION NUMBER,
MAX_ELEVATION NUMBER,
HEIGHT_DIFF  NUMBER,
"DURATION" VARCHAR2(50),
CREATED DATE,
TYPE VARCHAR2(10),
"UPDATED" DATE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(IDENT),
FOREIGN KEY(USER_ID) REFERENCES GTRAXXX.USERS(IDENT)
)TABLESPACE "GTRAXXX_DATA";


CREATE SEQUENCE GTRAXXX.TRACKS_SEQ START WITH 1;


grant all on GTRAXXX.TRACKS to GTRAXXX;
grant all on GTRAXXX.TRACKS_SEQ to GTRAXXX;
